services:
  application:
    build:
      context: .
    container_name: application
    env_file:
      - .env
    ports:
      - "8000:9091"
    depends_on:
      - postgres
  postgres:
    image: postgres:18.1
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"

volumes:
  pgdata: